language: node_js
sudo: required
dist: trusty
node_js: '9'
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
  - node_modules
before_script:
- npm run build
script:
- karma start --browsers ChromeHeadless,Firefox
